apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx
  namespace: dev
spec:
  releaseName: nginx
  chart:
    spec:
      chart: nginx
      version: 1.24.3
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 1m
  values:
    replicaCount: 2
    service:
      type: LoadBalancer
      port: 80
      targetPort: 80
    ingress:
      enabled: true
      hosts:
        - host: nginx.dev.example.com
          paths:
            - path: /
              pathType: Prefix
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi