apiVersion: v1
kind: Service
metadata:
  name: {{ include "weather-forecast.fullname" . }}
  labels:
    {{- include "weather-forecast.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
  selector:
    app: weather-forecast
